'''
user query: input

-------------------------Manager :----------------------
Plan: {
purpose: represents the research plan for researcher

req fields:
- main_topic (user query subject like Nvidia/OpenAI)
- research_points

owner node: Manager
}

------------------------Researcher:-----------------------------
--------------research orchestrator------------

Source: {
purpose : represents a discovered source of evidence

req fields:
- url

optional:
- domain

owner node: URLDiscoveryNode
}

Page: {
purpose: represents extracted content from source

req fields:
- url
- content

optional:
- title

owner node: PageReaderNode
}

Chunk: {
purpose: represents the smallest retrievable evidence unit

req fields:
- chunk_id
- url
- content

# url -> source traceability
# chunk_id -> chunk traceability

owner node: ChunkingNode
}

ResearchCorpus: {
purpose: represents all evidence available for research

req fields:
- chunks

owner node:
# not owned by a node
# constructed by Research Orchestrator
}

RetrievalResult: {
purpose: represents selected evidence for one research topic

req fields:
- topic
- retrieved_chunks

optional:
- retrieval_scores

owner node: RetrieverNode
}

Fact: {
purpose: represents a claim and its evidence

req fields:
- statement
- sources

owner node:
# created inside Finding
# generated by FindingGeneratorNode
}

Finding: {
purpose: represents synthesized knowledge extracted from evidence for a research topic

req fields:
- topic
- facts

owner node: FindingGeneratorNode
}

-------------------------Reporter:-------------------------------
ReportSection: {
purpose: final topic based content

req fields:
- topic
- content

owner node: Reporter
}

Report:{
purpose: final synthesized research output

req fields:
- title
- summary
- ReportSection

owner node: Reporter
}

************************************************Nodes*****************************************

--------------URLDiscoveryNode--------------
Input: Plan

Output: list[Source]

--------------PageReaderNode----------------
Input: list[Source]

Output: list[Page]

--------------ChunkingNode------------------
Input: list[Page]

Output: list[Chunk]

--------------ResearchCorpus----------------
Input: list[Chunk]

Output: ResearchCorpus

# object construction by orchestrator
# not an actual node

--------------RetrieverNode-----------------
Input: ResearchCorpus, topic

Output: RetrievalResult

---------------FindingGeneratorNode---------
Input: RetrievalResult

Output: Finding

----------------Reporter--------------------
Input: list[Finding]

Output: Report

'''
